Fix for issue 2211
eclipse-ee4j/eclipselink pull request #2289
Opened 2024-10-29 10:59 UTC by ajaypaul-ibm

This PR contains a fix for issue #2211. The query now correctly includes all primary keys instead of just one.

2024-10-30 09:10 UTC, rfelcman commented
Sorry this fix can't be accepted as tests 
`EclipseLink PR build / Test on JDK 21 (pull_request) ` `
continuous-integration/jenkins/pr-merge` are not passing please search test log outputs and modify Your code.

2024-11-11 14:07 UTC, rfelcman requested changes
I'm missing there tests. See mainly `JUnitJPQLFunctionsTest.java` or with `this` alias generation `JUnitJPQLJakartaDataNoAliasTest.java`

2024-11-11 14:58 UTC, ajaypaul-ibm commented
Hi @rfelcman 
 We have a few questions regarding this issue and have sent you an email with the details. Whenever you have a chance, could you kindly take a look?
Thank you very much for your time and help!

2024-11-12 07:11 UTC, ajaypaul-ibm commented
Hi @rfelcman  I went through the mail. Is  @IdClass is not supported in eclipse link?

2024-11-12 08:13 UTC, rfelcman commented
> Hi @rfelcman I went through the mail. Is @IdClass is not supported in EclipseLink?

Of course `@IdClass` it's supported in EclipseLink. Simply search code. You will find there a lot of examples in the tests. It just doesn't work with JPQL function `ID()` with multiple `@Id`s.

2024-11-21 04:42 UTC, ajaypaul-ibm commented
Hi @rfelcman I have send an mail can you please check it out ?

2024-12-09 15:54 UTC, ajaypaul-ibm commented
Hi @rfelcman 
I was able to identify the location in EclipseLink where accessors are being processed. Specifically, when an entity with @IdClass is encountered, it seems to fall into the last else case here: [MetadataDescriptor.java#L1542](https://github.com/eclipse-ee4j/eclipselink/blob/master/jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/MetadataDescriptor.java#L1542).

To handle this scenario, I attempted to add logic to check if the entity is using @IdClass. Below is an example of the extra else if block I added:
```
boolean isIdClass = accessor.getJavaClass().isAnnotationPresent("jakarta.persistence.IdClass", accessor.getClassAccessor());
else if (isIdClass) {
    if (accessor.isId()) {
        // Logic to handle @IdClass goes here
    }
}
```
However, I’m unsure of the specific logic that needs to go inside the if block to correctly process an entity with @IdClass.
Could you provide any hints or guidance on how to proceed?
Thank you for your help!

2024-12-11 09:09 UTC, rfelcman commented
> Hi @rfelcman I was able to identify the location in EclipseLink where accessors are being processed. Specifically, when an entity with @IdClass is encountered, it seems to fall into the last else case here: [MetadataDescriptor.java#L1542](https://github.com/eclipse-ee4j/eclipselink/blob/master/jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/MetadataDescriptor.java#L1542).
> 
> To handle this scenario, I attempted to add logic to check if the entity is using @IdClass. Below is an example of the extra else if block I added:
> 
> ```
> boolean isIdClass = accessor.getJavaClass().isAnnotationPresent("jakarta.persistence.IdClass", accessor.getClassAccessor());
> else if (isIdClass) {
>     if (accessor.isId()) {
>         // Logic to handle @IdClass goes here
>     }
> }
> ```
> 
> However, I’m unsure of the specific logic that needs to go inside the if block to correctly process an entity with @IdClass. Could you provide any hints or guidance on how to proceed? Thank you for your help.

I think, that _MetadataDescriptor.java_ is too generic. Try https://github.com/eclipse-ee4j/eclipselink/blob/2dd631c53a6b7369d8dca803b84e73248d21dd46/jpa/org.eclipse.persistence.jpa/src/main/java/org/eclipse/persistence/internal/jpa/metadata/accessors/classes/MappedSuperclassAccessor.java#L605
And another area where fix should be targeted is `org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.EmbeddedIdAccessor` or `org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.DerivedIdClassAccessor`

2025-01-21 13:37 UTC, rfelcman commented
https://github.com/eclipse-ee4j/eclipselink/pull/2287/files

2025-01-22 15:57 UTC, ajaypaul-ibm commented
Hi @rfelcman I have added unit test case . Please check

2025-02-19 09:41 UTC, rfelcman requested changes
After resolve code comments please rebase this PR against latest master and update copyright years in the file headers.

2025-02-19 09:41 UTC, rfelcman commented on foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/jpa/jpql/ReportItemBuilder.java
> +        if (multipleSelects || (expression.getSelectExpression()  instanceof IdExpression)) {
`(expression.getSelectExpression()  instanceof IdExpression)` is not correct pattern in this context. There should be new method with
```
    @Override
    public void visit(IdExpression expression) {
        multipleSelects = true;
        ...
    }
```

2025-02-19 09:41 UTC, rfelcman commented on jpa/eclipselink.jpa.testapps/jpa.test.jpql/src/test/java/org/eclipse/persistence/testing/tests/jpa/jpql/advanced/compositepk/JUnitJPQLComplexAggregateTest.java
> +        assertTrue("The result size should be greater than 0", !keys.isEmpty());
This test is not enough. Please add there asserts for a values.

2025-02-19 09:44 UTC, ajaypaul-ibm commented
@rfelcman Shall I make the changes and update the PR ?

2025-02-19 10:10 UTC, rfelcman commented
> @rfelcman Shall I make the changes and update the PR ?

Yes this is why PR technology exists plus hooked test calls which will verify modified code.

2025-02-19 12:33 UTC, rfelcman commented on foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/jpa/jpql/JPQLFunctionsAbstractBuilder.java
> +        if (!isEmbeddable(descriptor.getMappings())) {
Another comment: Maybe mentioned code should be optimized to remove some duplicitous calls.

2025-02-19 13:31 UTC, ajaypaul-ibm commented on foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/jpa/jpql/ReportItemBuilder.java
> +        if (multipleSelects || (expression.getSelectExpression()  instanceof IdExpression)) {
@rfelcman What should be the content of this method ?

2025-02-19 13:34 UTC, rfelcman commented on foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/jpa/jpql/ReportItemBuilder.java
> +        if (multipleSelects || (expression.getSelectExpression()  instanceof IdExpression)) {
I don't know, check other `public void visit(` as examples.

2025-02-20 06:17 UTC, ajaypaul-ibm commented on foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/jpa/jpql/ReportItemBuilder.java
> +        if (multipleSelects || (expression.getSelectExpression()  instanceof IdExpression)) {
@rfelcman Do you mean to check whether the expression is an instance of IdExpression inside visit() method ?

2025-02-21 07:27 UTC, rfelcman commented
I don't see any changes in the code -> no any reason to review it again.

2025-02-21 07:31 UTC, rfelcman commented on foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/jpa/jpql/ReportItemBuilder.java
> +        if (multipleSelects || (expression.getSelectExpression()  instanceof IdExpression)) {
> @rfelcman Do you mean to check whether the expression is an instance of IdExpression inside visit() method ?

Yes. Main reason is eliminate `|| (expression.getSelectExpression()  instanceof IdExpression)` by new `public void visit(IdExpression expression) {` method which is called automaticaly by visitor pattern.

2025-03-04 09:30 UTC, ajaypaul-ibm commented
@rfelcman Can you please check now

2025-03-04 13:45 UTC, rfelcman commented on foundation/org.eclipse.persistence.core/src/main/java/org/eclipse/persistence/internal/jpa/jpql/ReportItemBuilder.java
> +        multipleSelects = true;
There must be additional code like `addAttribute` or `expression.accept` or ...

2025-03-21 15:15 UTC, rfelcman commented
See #2384 2384

2025-04-01 13:04 UTC, closed without merging